name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: true             # Ativa o envio para Cypress Dashboard
          parallel: false          # Ajuste se quiser rodar paralelo
          group: 'GitHub Actions' # Nome do grupo no Dashboard
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
