name: Cypress Tests

on:
    push:
        branches: [main, master]
        paths-ignore:
          - 'README.md'        # Ignora commits que alteram apenas o README
          - 'documentos_relatorios_desenvolvidos/**' # Ignorar a pasta e subpastas
    pull_request:
        branches: [main, master]
        paths-ignore:
          - 'README.md'        # Ignora commits que alteram apenas o README
          - 'documentos_relatorios_desenvolvidos/**' # Ignorar a pasta e subpastas
    workflow_dispatch:
jobs:
    test:
        timeout-minutes: 120
        runs-on: ubuntu-latest
        strategy:
          matrix:
            browser: [firefox]        
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci

            - name: Verify Cypress installation
              run: npx cypress verify

            - name: Run Cypress tests
              uses: cypress-io/github-action@v5
              with:
                  browser: ${{ matrix.browser }}              
                  record: true                 # envia resultados para o Cypress Dashboard
                  parallel: true              # ajuste se quiser rodar paralelo
                  group: "GitHub Actions - ${{ matrix.browser }}"  # nome do grupo no Dashboard
        env:
             CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
